// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SuperAdminCreator is an autogenerated mock type for the SuperAdminCreator type
type SuperAdminCreator struct {
	mock.Mock
}

type SuperAdminCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *SuperAdminCreator) EXPECT() *SuperAdminCreator_Expecter {
	return &SuperAdminCreator_Expecter{mock: &_m.Mock}
}

// CreateSuperAdmin provides a mock function with no fields
func (_m *SuperAdminCreator) CreateSuperAdmin() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateSuperAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SuperAdminCreator_CreateSuperAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuperAdmin'
type SuperAdminCreator_CreateSuperAdmin_Call struct {
	*mock.Call
}

// CreateSuperAdmin is a helper method to define mock.On call
func (_e *SuperAdminCreator_Expecter) CreateSuperAdmin() *SuperAdminCreator_CreateSuperAdmin_Call {
	return &SuperAdminCreator_CreateSuperAdmin_Call{Call: _e.mock.On("CreateSuperAdmin")}
}

func (_c *SuperAdminCreator_CreateSuperAdmin_Call) Run(run func()) *SuperAdminCreator_CreateSuperAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SuperAdminCreator_CreateSuperAdmin_Call) Return(_a0 error) *SuperAdminCreator_CreateSuperAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SuperAdminCreator_CreateSuperAdmin_Call) RunAndReturn(run func() error) *SuperAdminCreator_CreateSuperAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// NewSuperAdminCreator creates a new instance of SuperAdminCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSuperAdminCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *SuperAdminCreator {
	mock := &SuperAdminCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
